env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - prettier
rules:
  prettier/prettier: [error] # Prettierのルール違反をエラーとして扱う
  eact/prop-types: off # Reactのprop-typesを無効化
settings:
  react:
    version: detect # Reactのバージョンを自動検出
