openapi: 3.0.3
info:
  title: ToDo API
  version: 1.0.0
  description: ToDo アプリケーションの API

servers:
  - url: http://localhost:5000/

paths:
  /todos:
    get:
      summary: ToDoの一覧
      responses:
        '200':
          description: 取得成功レスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
        '404':
          description: 取得失敗レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: ToDoを1件追加
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '201':
          description: 登録成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '400':
          description: リクエスト不正レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /todos/{id}:
    put:
      summary: ToDoを1件更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '200':
          description: 更新成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '404':
          description: 指定されたidのToDoが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: ToDoを1件削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 削除成功レスポンス
        '404':
          description: 指定されたidのToDoが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ToDo:
      type: object
      required:
        - id
        - task
      properties:
        id:
          type: integer
          format: int64
        task:
          type: string
        completed:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
